# ──────────────────────────────────────────────────────────────
# Composite action: shared Xcode + simulator + tool setup
# Avoids duplicating these steps across every CI job.
# ──────────────────────────────────────────────────────────────

name: Setup Xcode Environment
description: Select Xcode, resolve simulator, install tools, and restore caches.

inputs:
  install-xcbeautify:
    description: Whether to install xcbeautify
    required: false
    default: "true"
  install-swiftlint:
    description: Whether to install SwiftLint
    required: false
    default: "false"

outputs:
  destination:
    description: Resolved Xcode destination string
    value: ${{ steps.resolve-sim.outputs.destination }}

runs:
  using: composite
  steps:
    - name: Select Xcode
      shell: bash
      run: |
        XCODE_PATH=$(ls -d /Applications/Xcode*.app 2>/dev/null | sort -V | tail -1)
        echo "Using Xcode at: $XCODE_PATH"
        sudo xcode-select -s "$XCODE_PATH"
        xcodebuild -version

    - name: Resolve simulator destination
      id: resolve-sim
      shell: bash
      run: |
        DEST=$(xcrun simctl list devices available -j | python3 -c "
        import json, sys
        data = json.load(sys.stdin)
        candidates = []
        for runtime, devices in data['devices'].items():
            for d in devices:
                if 'iPhone' in d['name'] and d['isAvailable']:
                    candidates.append((runtime, d['name']))
        candidates.sort(key=lambda x: x[0], reverse=True)
        for runtime, name in candidates:
            if 'iPhone 16' in name:
                print(name); sys.exit(0)
        for runtime, name in candidates:
            if 'iPhone' in name:
                print(name); sys.exit(0)
        sys.exit(1)
        ")
        echo "Resolved simulator: $DEST"
        echo "destination=platform=iOS Simulator,name=$DEST,OS=latest" >> "$GITHUB_OUTPUT"

    # ── Homebrew tool cache ────────────────────────────────
    - name: Cache Homebrew packages
      if: inputs.install-xcbeautify == 'true' || inputs.install-swiftlint == 'true'
      uses: actions/cache@v4
      with:
        path: |
          ~/Library/Caches/Homebrew
          /opt/homebrew/Cellar/xcbeautify
          /opt/homebrew/Cellar/swiftlint
        key: brew-${{ runner.os }}-${{ inputs.install-xcbeautify }}-${{ inputs.install-swiftlint }}-v1

    - name: Install xcbeautify
      if: inputs.install-xcbeautify == 'true'
      shell: bash
      run: command -v xcbeautify &>/dev/null || brew install xcbeautify

    - name: Install SwiftLint
      if: inputs.install-swiftlint == 'true'
      shell: bash
      run: command -v swiftlint &>/dev/null || brew install swiftlint
